### ISSUE TITLE
Tracking: Add dependabot to update Github Action versions

### ISSUE THREAD

**Issue by alexfikl** [inducer/ci-support#31]
This just makes a list of all the repos that still need to be dependabot-enabled (see https://github.com/inducer/pytential/pull/226#issuecomment-2043160399). This just means adding a file at `.github/dependabot.yml` with
```
version: 2
updates:
    # Set update schedule for GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"

# vim: sw=4
``` 
(mostly complete list:)
* [X] arraycontext
* [x] boxtree https://github.com/inducer/boxtree/pull/80
* [x] cgen https://github.com/inducer/cgen/pull/45
* [x] codepy https://github.com/inducer/codepy/pull/42
* [x] dagrt https://github.com/inducer/dagrt/pull/37
* [x] genpy https://github.com/inducer/genpy/pull/16
* [x] gmsh_interop https://github.com/inducer/gmsh_interop/pull/28
* [x] grudge
* [x] islpy https://github.com/inducer/islpy/pull/128
* [x] leap https://github.com/inducer/leap/pull/35
* [x] loopy https://github.com/inducer/loopy/pull/834
* [x] meshmode
* [x] meshpy https://github.com/inducer/meshpy/pull/90
* [x] modepy
* [x] pudb https://github.com/inducer/pudb/pull/646
* [x] pyfmmlib https://github.com/inducer/pyfmmlib/pull/25
* [x] pymbolic
* [x] pymetis https://github.com/inducer/pymetis/pull/63
* [x] pyopencl https://github.com/inducer/pyopencl/pull/724
* [x] pytato https://github.com/inducer/pytato/pull/492
* [X] pytential
* [x] pytools https://github.com/inducer/pytools/pull/215
* [x] pyvisfile
* [x] sumpy https://github.com/inducer/sumpy/pull/193

**Comment by inducer** [comment]
Thanks for helping stem the tide!

**Comment by alexfikl** [comment]
@inducer With `pytato` and `pudb`, this should now be done. Did I miss anything?

**Comment by inducer** [comment]
Don't think so. And even if so: it can always be done later. :)
